NOGIZAKA = {
    # 1st
    '秋元真夏': ['あきもと まなつ', 'manatsu.akimoto'],
    # '安藤美雲': ['あんどう みくも', 'mikumo.ando'],
    '生田絵梨花': ['いくた えりか', 'erika.ikuta'],
    # '生駒里奈': ['いこま りな', 'rina.ikoma'],
    # '市來玲奈': ['いちき れな', 'rena.ichiki'],
    # '伊藤寧々': ['いとう ねね', 'nene.ito'],
    # '伊藤万理華': ['いとう まりか', 'marika.ito'],
    '井上小百合': ['いのうえ さゆり', 'sayuri.inoue'],
    # '衛藤美彩': ['えとう みさ', 'misa.eto'],
    # '柏幸奈': ['かしわ ゆきな', 'yukina.kashiwa'],
    # '川後陽菜': ['かわご ひな', 'hina.kawago'],
    # '川村真洋': ['かわむら まひろ', 'mahiro.kawamura'],
    '齋藤飛鳥': ['さいとう あすか', 'asuka.saito'],
    # '斎藤ちはる': ['さいとう ちはる', 'chiharu.saito'],
    '斉藤優里': ['さいとう ゆうり', 'yuuri.saito'],
    '桜井玲香': ['さくらい れいか', 'reika.sakurai'],
    '白石麻衣': ['しらいし まい', 'mai.shiraishi'],
    '高山一実': ['たかやま かずみ', 'kazumi.takayama'],
    '中田花奈': ['なかだ かな', 'kana.nakada'],
    # '中元日芽香': ['なかもと ひめか', 'himeka.nakamoto'],
    # '永島聖羅': ['ながしま せいら', 'seira.nagashima'],
    # '西野七瀬': ['にしの ななせ', 'nanase.nishino'],
    # '能條愛未': ['のうじょう あみ', 'ami.noujo'],
    # '橋本奈々未': ['はしもと ななみ', 'nanami.hashimoto'],
    # '畠中清羅': ['はたなか せいら', 'seira.hatanaka'],
    '樋口日奈': ['ひぐち ひな', 'hina.higuchi'],
    # '深川麻衣': ['ふかがわ まい', 'mai.fukagawa'],
    '星野みなみ': ['ほしの みなみ', 'minami.hoshino'],
    '松村沙友理': ['まつむら さゆり', 'sayuri.matsumura'],
    # '宮澤成良': ['みやざわ せいら', 'seira.miyazawa'],
    # '大和里菜': ['やまと りな', 'rina.yamato'],
    # '若月佑美': ['わかつき ゆみ', 'yumi.wakatsuki'],
    '和田まあや': ['わだ まあや', 'maaya.wada'],

    # 2nd
    '伊藤かりん': ['いとう かりん', 'karin.itou'],
    '伊藤純奈': ['いとう じゅんな', 'junna.itou'],
    '北野日奈子': ['きたの ひなこ', 'hinako.kitano'],
    # "相楽伊織": ["さがら いおり", "iori.sagara"],
    '佐々木琴子': ['ささき ことこ', 'kotoko.sasaki'],
    '新内眞衣': ['しんうち まい', 'mai.shinuchi'],
    '鈴木絢音': ['すずき あやね', 'ayane.suzuki'],
    '寺田蘭世': ['てらだ らんぜ', 'ranze.terada'],
    '堀未央奈': ['ほり みおな', 'miona.hori'],
    '山崎怜奈': ['やまざき れな', 'rena.yamazaki'],
    '渡辺みり愛': ['わたなべ みりあ', 'miria.watanabe'],
    # 3rd
    '伊藤理々杏': ['いとう りりあ', 'riria.itou'],
    '岩本蓮加': ['いわもと れんか', 'renka.iwamoto'],
    '梅澤美波': ['うめざわ みなみ', 'minami.umezawa'],
    '大園桃子': ['おおぞの ももこ', 'momoko.oozono'],
    '久保史緒里': ['くぼ しおり', 'shiori.kubo'],
    '阪口珠美': ['さかぐち たまみ', 'tamami.sakaguchi'],
    '佐藤楓': ['さとう かえで', 'kaede.satou'],
    '中村麗乃': ['なかむら れの', 'reno.nakamura'],
    '向井葉月': ['むかい はづき', 'hazuki.mukai'],
    '山下美月': ['やました みづき', 'mizuki.yamashita'],
    '吉田綾乃クリスティー': ['よしだ あやのくりすてぃー', 'ayanochristie.yoshida'],
    '与田祐希': ['よだ ゆうき', 'yuuki.yoda'],
}


KEYAKIZAKA = {
    # TODO: Update Member list
    u"長濱ねる": [u"ながはま ねる", "nagahama-neru"],
    u"東村芽依": [u"ひがしむら めい", "higashimura-mei"],
    u"石森虹花": [u"いしもり にじか", "ishimori-nijika"],
    u"今泉佑唯": [u"いまいずみ ゆい", "imaizumi-yui"],
    u"上村莉菜": [u"うえむら りな", "uemura-rina"],
    u"尾関梨香": [u"おぜき りか", "ozeki-rika"],
    u"織田奈那": [u"おだ なな", "oda-nana"],
    u"小池美波": [u"こいけ みなみ", "koike-minami"],
    u"小林由依": [u"こばやし ゆい", "kobayashi-yui"],
    u"齋藤冬優花": [u"さいとう ふゆか", "saitou-fuyuka"],
    u"佐藤詩織": [u"さとう しおり", "satou-shiori"],
    u"志田愛佳": [u"しだ まなか", "shida-manaka"],
    u"菅井友香": [u"すがい ゆうか", "sugai-yuuka"],
    u"鈴本美愉": [u"すずもと みゆ", "suzumoto-miyu"],
    u"長沢菜々香": [u"ながさわ ななこ", "nagasawa-nanako"],
    u"土生瑞穂": [u"はぶ みづほ", "habu-mizuho"],
    u"原田葵": [u"はらだ あおい", "harada-aoi"],
    u"平手友梨奈": [u"ひらて ゆりな", "hirate-yurina"],
    u"守屋茜": [u"もりや あかね", "moriya-akane"],
    u"米谷奈々未": [u"よねたに ななみ", "yonetani-nanami"],
    u"渡辺梨加": [u"わたなべ りか", "watanabe-rika"],
    u"渡邉理佐": [u"わたなべ りさ", "watanabe-risa"]
}

HINATAZAKA = {
    # TODO: Update Member list
    u"井口眞緒": [u"いぐち まお", "iguchi-mao"],
    u"潮紗理菜": [u"うしお さりな", "ushio-sarina"],
    u"柿崎芽実": [u"かきざき めみ", "kakizaki-memi"],
    u"影山優佳": [u"かげやま ゆうか", "kageyama-yuuka"],
    u"加藤史帆": [u"かとう しほ", "katou-shiho"],
    u"齊藤京子": [u"さいとう きょうこ", "saitou-kyouko"],
    u"佐々木久美": [u"ささき くみ", "sasaki-kumi"],
    u"佐々木美玲": [u"ささき みれい", "sasaki-mirei"],
    u"高瀬愛奈": [u"たかせ まな", "takase-mana"],
    u"高本彩花": [u"たかもと あやか", "takamoto-ayaka"],
}
